version: '3.8'

services:
  # Spring Boot Application Service
  app:
    image: jhona1dev/animal-api:latest
    container_name: animal-api
    ports:
      - '8084:8084'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - demo-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  # MySQL Database Service
  mysql:
    depends_on:
      - app
    image: 'mysql:8.0'
    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: mydatabase # for k8s goes to the config-map
      MYSQL_USER: myuser # for k8s goes to the secret
      MYSQL_PASSWORD: secret # for k8s goes to the secret
      MYSQL_ROOT_PASSWORD: verysecret # for k8s goes to the secret
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pverysecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  demo-network:
    driver: bridge

volumes:
  mysql-data: