apiVersion: v1
kind: Secret # Kind is the service to use for k8s in this case is secret service
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque # Opaque is based on key-value pair
data:
  mysql-user: bXl1c2Vy # user encrypted
  mysql-password: c2VjcmV0 # password encrypted
  mysql-root-password: dmVyeXNlY3JldA== #root password encrypted
