apiVersion: v1
kind: Service
metadata:
  name: animal-api
  labels:
    app: animal-api
spec:
  type: LoadBalancer  # (external service for animal-api)
  selector:
    app: animal-api
  ports:
  - port: 80        # Port exposed outside the k8s by the service: this port forward the traffic to the targetPort witch is container port used inside the application containerized(pod)
    targetPort: http  # Port on the container in this case is reference by name from api-deployment container port:8084 this is useful due to when you change your port number into your application does not need hardcoding the value here in the service 'cause http already reference to the new value
    protocol: TCP
    name: http