apiVersion: v1
kind: Service
metadata:
  name: animal-api
  labels:
    app: animal-api
spec:
  type: LoadBalancer  # (external service for animal-api)
  selector:
    app: animal-api
  ports:
  - port: 8084        # Port exposed by the service
    targetPort: 8084  # Port on the container
    protocol: TCP
    name: http