spring:
  application:
    name: ${SPRING_APPLICATION_NAME:demo}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:${MYSQL_PORT}/${MYSQL_DATABASE_NAME_APP}}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialecta

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8084}
