apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP # Internal service - only accessible within the cluster  (by default is ClusterIp)
  selector:
    app: mysql
  ports:
  - port: 3306 # read api-deployment there you will find the meaning for this section
    targetPort: mysql # read api-deployment there you will find the meaning for this section
    protocol: TCP
    name: mysql
